USE[master]
GO
/****** Object:  Database [PartyProduct]    Script Date: 20-11-2023 09:00:09 AM ******/
CREATE DATABASE [PartyProduct]
CONTAINMENT = NONE
 ON PRIMARY
(NAME = N'PartyProduct', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PartyProduct.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
(NAME = N'PartyProduct_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PartyProduct_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PartyProduct] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC[PartyProduct].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PartyProduct] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PartyProduct] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PartyProduct] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PartyProduct] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PartyProduct] SET ARITHABORT OFF 
GO
ALTER DATABASE [PartyProduct] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PartyProduct] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PartyProduct] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PartyProduct] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PartyProduct] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PartyProduct] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PartyProduct] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PartyProduct] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PartyProduct] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PartyProduct] SET DISABLE_BROKER 
GO
ALTER DATABASE [PartyProduct] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PartyProduct] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PartyProduct] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PartyProduct] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PartyProduct] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PartyProduct] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PartyProduct] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PartyProduct] SET RECOVERY FULL 
GO
ALTER DATABASE [PartyProduct] SET MULTI_USER 
GO
ALTER DATABASE [PartyProduct] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PartyProduct] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PartyProduct] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF)
GO
ALTER DATABASE [PartyProduct] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PartyProduct] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PartyProduct] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PartyProduct', N'ON'
GO
ALTER DATABASE [PartyProduct] SET QUERY_STORE = OFF
GO
USE [PartyProduct]
GO
/****** Object:  Table [dbo].[Assign_Party]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assign_Party](
    [Party_id][decimal](18, 0) NOT NULL,
    [Product_id][decimal](18, 0) NOT NULL,
 CONSTRAINT[IX_Assign_Party] UNIQUE NONCLUSTERED
(
    [Party_id] ASC,
    [Product_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Invoice]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoice](
    [Invoice_id][decimal](18, 0) IDENTITY(1, 1) NOT NULL,
    [Party_Name][varchar](50) NOT NULL,
    [Product_Name][varchar](50) NOT NULL,
    [Rate][decimal](18, 0) NOT NULL,
    [Quantity][decimal](18, 0) NOT NULL,
    [Total]  AS([Rate] * [Quantity]),
 CONSTRAINT[PK_Invoice] PRIMARY KEY CLUSTERED
(
    [Invoice_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Party]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Party](
    [Party_id][decimal](18, 0) IDENTITY(1, 1) NOT NULL,
    [Party_Name][nvarchar](50) NOT NULL,
 CONSTRAINT[PK_Party] PRIMARY KEY CLUSTERED
(
    [Party_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY],
 CONSTRAINT[IX_Party_1] UNIQUE NONCLUSTERED
(
    [Party_Name] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
    [Product_id][decimal](18, 0) IDENTITY(1, 1) NOT NULL,
    [Product_Name][nvarchar](50) NOT NULL,
 CONSTRAINT[PK_Product] PRIMARY KEY CLUSTERED
(
    [Product_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Product_Rate]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product_Rate](
    [Rate_id][int] IDENTITY(1, 1) NOT NULL,
    [Product_id][decimal](18, 0) NOT NULL,
    [Rate][decimal](18, 0) NOT NULL,
    [Rate_Date][date] NOT NULL,
 CONSTRAINT[PK_Product_Rate] PRIMARY KEY CLUSTERED
(
    [Rate_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY],
 CONSTRAINT[IX_Product_Rate] UNIQUE NONCLUSTERED
(
    [Product_id] ASC,
    [Rate] ASC,
    [Rate_Date] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[TempInvoice]    Script Date: 20-11-2023 09:00:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TempInvoice](
    [Invoice_id][decimal](18, 0) IDENTITY(1, 1) NOT NULL,
    [Party_Name][varchar](50) NOT NULL,
    [Product_Name][varchar](50) NOT NULL,
    [Rate][decimal](18, 0) NOT NULL,
    [Quantity][decimal](18, 0) NOT NULL,
    [Total]  AS([Rate] * [Quantity])
) ON[PRIMARY]
GO
/****** Object:  Index [IX_Invoice_1]    Script Date: 20-11-2023 09:00:10 AM ******/
CREATE NONCLUSTERED INDEX [IX_Invoice_1] ON[dbo].[Invoice]
(
    [Invoice_id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Product]    Script Date: 20-11-2023 09:00:10 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Product] ON[dbo].[Product]
(
    [Product_Name] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
GO
ALTER TABLE [dbo].[Assign_Party]  WITH CHECK ADD  CONSTRAINT [FK_Assign_Party_Party] FOREIGN KEY([Party_id])
REFERENCES[dbo].[Party]([Party_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Assign_Party] CHECK CONSTRAINT[FK_Assign_Party_Party]
GO
ALTER TABLE [dbo].[Assign_Party]  WITH CHECK ADD  CONSTRAINT [FK_Assign_Party_Product] FOREIGN KEY([Product_id])
REFERENCES[dbo].[Product]([Product_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Assign_Party] CHECK CONSTRAINT[FK_Assign_Party_Product]
GO
ALTER TABLE [dbo].[Party]  WITH CHECK ADD  CONSTRAINT [FK_Party_Party] FOREIGN KEY([Party_id])
REFERENCES[dbo].[Party]([Party_id])
GO
ALTER TABLE [dbo].[Party] CHECK CONSTRAINT[FK_Party_Party]
GO
ALTER TABLE [dbo].[Party]  WITH CHECK ADD  CONSTRAINT [FK_Party_Party1] FOREIGN KEY([Party_id])
REFERENCES[dbo].[Party]([Party_id])
GO
ALTER TABLE [dbo].[Party] CHECK CONSTRAINT[FK_Party_Party1]
GO
ALTER TABLE [dbo].[Product_Rate]  WITH CHECK ADD  CONSTRAINT [FK_Product_Rate_Product1] FOREIGN KEY([Product_id])
REFERENCES[dbo].[Product]([Product_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Product_Rate] CHECK CONSTRAINT[FK_Product_Rate_Product1]
GO
ALTER TABLE [dbo].[Product_Rate]  WITH CHECK ADD  CONSTRAINT [CK_Product_Rate] CHECK  (([Rate]>(0)))
GO
ALTER TABLE [dbo].[Product_Rate] CHECK CONSTRAINT[CK_Product_Rate]
GO
USE [master]
GO
ALTER DATABASE [PartyProduct] SET READ_WRITE 
GO
